"""create favorites table

Revision ID: 02016575c12f
Revises: 1c3399e8f064
Create Date: 2022-04-28 10:20:14.430447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
#
# revision identifiers, used by Alembic.
revision = '02016575c12f'
down_revision = '1c3399e8f064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.drop_table('feed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('feed_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('publication_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='feed_user_id_fkey'),
    sa.PrimaryKeyConstraint('feed_id', name='feed_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
