"""create column confirmed in user modedel

Revision ID: 054695a82930
Revises: b567430dbed8
Create Date: 2022-05-05 19:01:17.650981

"""
from alembic import op
import sqlalchemy as sa

#
# revision identifiers, used by Alembic.
revision = '054695a82930'
down_revision = 'b567430dbed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
