"""change status in model_recipe to text

Revision ID: 1c3399e8f064
Revises: 425fd5c6bca6
Create Date: 2022-04-27 16:08:06.474027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

#
# revision identifiers, used by Alembic.
revision = "1c3399e8f064"
down_revision = "6eacc178a403"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipes",
        "method",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipes",
        "method",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
