"""create relationship user-recipe

Revision ID: 35f410b9386b
Revises: 1c3399e8f064
Create Date: 2022-04-28 10:21:26.124516

"""
from alembic import op
import sqlalchemy as sa

#
# revision identifiers, used by Alembic.
revision = '35f410b9386b'
down_revision = '1c3399e8f064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ingredient_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('recipe_ingredient',
    sa.Column('recipe_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('QUILO', 'GRAMA', 'LITRO', 'MILILITRO', 'XICARA', 'COLHER', 'UNIDADE', name='unitenum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], ),
    sa.PrimaryKeyConstraint('recipe_ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredient')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
