"""change user_id in recipe_model to uuid

Revision ID: 37bca2ed507f
Revises: 9a348ccb06a4
Create Date: 2022-04-26 21:07:17.825376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "37bca2ed507f"
down_revision = "8d3c2b3de53e"
branch_labels = None
depends_on = None
#


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column(
            "status", sa.Enum("NOT_VERIFIED", "VERIFIED", name="myenum"), nullable=False
        ),
        sa.Column("serves", sa.Integer(), nullable=False),
        sa.Column("img_link", sa.String(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("recipe_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipes")
    # ### end Alembic commands ###
