"""create recipe_ingredient table

Revision ID: 499b5ea1e61a
Revises: 425fd5c6bca6
Create Date: 2022-04-27 17:32:12.160936

"""
from alembic import op
import sqlalchemy as sa

#
# revision identifiers, used by Alembic.
revision = '499b5ea1e61a'
down_revision = '425fd5c6bca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredient',
    sa.Column('recipe_ingredient_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('QUILO', 'GRAMA', 'LITRO', 'MILILITRO', 'XICARA', 'COLHER', 'UNIDADE', name='unitenum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], ),
    sa.PrimaryKeyConstraint('recipe_ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredient')
    # ### end Alembic commands ###
