"""inclusion of the publication attribute in the feed table

Revision ID: a803001f6c08
Revises: 02016575c12f
Create Date: 2022-04-28 15:06:42.876955

"""
from alembic import op
import sqlalchemy as sa

#
# revision identifiers, used by Alembic.
revision = 'a803001f6c08'
down_revision = '02016575c12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('publication', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed', 'publication')
    # ### end Alembic commands ###
