"""refactor recipe_ingredient table

Revision ID: b567430dbed8
Revises: da737fbbc191
Create Date: 2022-04-29 14:16:38.749654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
#
# revision identifiers, used by Alembic.
revision = 'b567430dbed8'
down_revision = 'da737fbbc191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe_ingredient', 'unit',
               existing_type=postgresql.ENUM('QUILO', 'GRAMA', 'LITRO', 'MILILITRO', 'XICARA', 'COLHER', 'UNIDADE', name='unitenum'),
               nullable=True)
    op.alter_column('recipe_ingredient', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe_ingredient', 'amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('recipe_ingredient', 'unit',
               existing_type=postgresql.ENUM('QUILO', 'GRAMA', 'LITRO', 'MILILITRO', 'XICARA', 'COLHER', 'UNIDADE', name='unitenum'),
               nullable=False)
    # ### end Alembic commands ###
