"""fix: change in the foreign key of the recipe_id

Revision ID: da737fbbc191
Revises: 02016575c12f
Create Date: 2022-04-28 16:22:14.024455

"""
from alembic import op
import sqlalchemy as sa

#
# revision identifiers, used by Alembic.
revision = 'da737fbbc191'
down_revision = 'a803001f6c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('reciped_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorites', 'recipes', ['reciped_id'], ['recipe_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'reciped_id')
    # ### end Alembic commands ###
